### ISSUE TITLE
Not Working (node.js and ejs)

### ISSUE THREAD

**Issue by EmanuelRodriguezBedeman** [coliff/dark-mode-switch#118]
Hello! 

I installed the package using npm and followed the documentation (readme.md) and it doesn't work, I don't see it adding the class to the body or any other tag.

Did I did something wrong?

**Comment by coliff** [comment]
Heya. The demo is working: https://coliff.github.io/dark-mode-switch/

The code for that page is in the repo: https://github.com/coliff/dark-mode-switch/blob/main/index.html

I'd suggest downloading that and working from there.

**Comment by EmanuelRodriguezBedeman** [comment]
I'll try out again, have you tried using it on node.js and ejs? That's the tech I'm trying to make it work.

**Comment by coliff** [comment]
No, I've just used it with Angular and static HTML sites (built with Hugo). But I've seen it working with React sites and so I'm you should be able to get it working. Make sure the JS is loaded in the right order. Check the dev tools console for clues if any issues. Good luck! :-)

**Comment by EmanuelRodriguezBedeman** [comment]
Thank you very much coliff, I'll post a workaround once I make it work. Thank you very much!
