### ISSUE TITLE
HTML hyperlink integration?

### ISSUE THREAD

**Issue by techtreehouse** [coliff/dark-mode-switch#193]
Hi, how can I make a hyperlink so that when I click on the link, it loads the js script and turns on dark mode?
Sorry, the solution might be easy but I haven't found a solution yet.

**Comment by coliff** [comment]
Hi. One technique I like using for things like this is to append an URL parameter to the URL... e.g. `?darkmode=on`. When the page loads it can detect the presence of this in the URL and add a parameter to the body, maybe something along the lines of this:

```
<script>
// if URL has parameter `?darkmode=on`, add `data-theme="dark"` to the `body`
  if (window.location.search.includes('darkmode=on')) {
    document.body.setAttribute('data-theme', 'dark');
  }
</script>
```

**Comment by techtreehouse** [comment]
> Hi. One technique I like using for things like this is to append an URL parameter to the URL... e.g. `?darkmode=on`. When the page loads it can detect the presence of this in the URL and add a parameter to the body, maybe something along the lines of this:
> 
> ```
> <script>
> // if URL has parameter `?darkmode=on`, add `data-theme="dark"` to the `body`
>   if (window.location.search.includes('darkmode=on')) {
>     document.body.setAttribute('data-theme', 'dark');
>   }
> </script>
> ```

Hi, thank you for your speedy reply. I forgot to clarify that the hyperlink is already in the navigation bar of the same website the darkmode occurs on. I'm trying to create a sort of label/href button so when clicked, darkmode instantly turns on, without any reloading of the page. I have tried using a checkbox and styling that to look nicer with CSS, but I would much rather just the label "Dark Mode" without any checkbox at all. Thank you for your help so far!

**Comment by coliff** [comment]
I made a working demo for you :-)  It doesn't need any JavaScript at all! Check the HTML & CSS

https://coliff.github.io/dark-mode-switch-test/

**Comment by techtreehouse** [comment]
> I made a working demo for you :-) It doesn't need any JavaScript at all! Check the HTML & CSS
> 
> https://coliff.github.io/dark-mode-switch-test/

Hi coliff, thank you for dedicating your time and effort to create a demo for me. One more thing, how does the demo you've provided call the JS file? I can't seem to find how dark mode is turned on when clicking it. I would need to know as it tries to find the file using the current URL+dark-mode-switch.min.js, even though my JS file is stored under the baseurl. I fixed this before by setting the src in the <script> tag to the exact location of the JS file under my website, but since now there is no <script> tag, I don't know how to fix this. Thank you for your excellent help so far!

**Comment by coliff** [comment]
The demo above doesn't use or need any JavaScript at all! It uses the `:has` CSS selector. If the toggle is checked it can set the dark mode colors.

REF:
- https://developer.mozilla.org/en-US/docs/Web/CSS/:has
- https://caniuse.com/css-has

```css
body:has(#darkModeToggle:checked) {
  background-color: #333 !important;
  color: #eee;
}

body:has(#darkModeToggle:checked) .nav-masthead .nav-link {
  color: #eee;
}
```

**Comment by techtreehouse** [comment]
> The demo above doesn't use or need any JavaScript at all! It uses the `:has` CSS selector. If the toggle is checked it can set the dark mode colors.
> 
> REF:
> 
> * https://developer.mozilla.org/en-US/docs/Web/CSS/:has
> * https://caniuse.com/css-has
> 
> ```css
> body:has(#darkModeToggle:checked) {
>   background-color: #333 !important;
>   color: #eee;
> }
> 
> body:has(#darkModeToggle:checked) .nav-masthead .nav-link {
>   color: #eee;
> }
> ```

Oh wow! I did not know that's possible! Sorry for bugging you so much, but how can I remove that little padding/gap on the left side of the label, without destroying functionality?

**Comment by coliff** [comment]
updated the demo with that fix

**Comment by techtreehouse** [comment]
> updated the demo with that fix

Thanks coliff! This works really well.
