### ISSUE TITLE
Bootstrap Nav Link colors not changing in Dark Mode

### ISSUE THREAD

**Issue by Joydeycdvs** [coliff/dark-mode-switch#21]
![Screenshot (114)](https://user-images.githubusercontent.com/33337707/70155638-a4b08400-16d8-11ea-9226-004d1d3f0c29.png)

**Comment by coliff** [comment]
You can (and should!) modify the dark-theme styles. For example you might want to add:
```
[data-theme="dark"] .nav-link {
  color: #fff !important;
}
```

**Comment by IrvingSG** [comment]
Does it works with Bootstrap cards?
