### ISSUE TITLE
Not working on latest Firefox

### ISSUE THREAD

**Issue by maxsupermanhd** [coliff/dark-mode-switch#24]
Throws this error on console and not doing anything:
`SecurityError: The operation is insecure.`

**Comment by coliff** [comment]
It's working correctly for me on Firefox 75 on both Windows 10 and macOS. Can you please retest? If an issue still, do you have a site/page to test?

**Comment by maxsupermanhd** [comment]
Lmao ok, it's working now... And now security error. And I did whole nothing with this thing.
