### ISSUE TITLE
Apply to modals

### ISSUE THREAD

**Issue by mattfleaydaly** [coliff/dark-mode-switch#28]
What's the easiest way to apply this to modals also?

**Comment by coliff** [comment]
hey there. Sorry for the delay in replying. I think you could add some CSS like this:

```
    [data-theme="dark"] .modal-content {
      background-color: #333;
    }

    [data-theme="dark"] .modal-header,
    [data-theme="dark"] .modal-content,
    [data-theme="dark"] .modal-footer {
      border-color: #222;
    }
```

That'll set the background of the modal to a dark grey (I think you'd want it to be a lighter color than black) and also darken the borders.

Quick demo here: https://tests.christianoliff.com/dark-mode-switch-modals/index.html
