### ISSUE TITLE
Update To Bootstrap 5

### ISSUE THREAD

**Issue by 9mido** [coliff/dark-mode-switch#32]
In alpha mode currently but would be nice to get a head start. Maybe make a separate package for it.

https://v5.getbootstrap.com/

**Comment by coliff** [comment]
yep! I'd thought about this already. I'll definitely look into this. I think it'll be easy to do with just an updated example and no JS changes.

I'm currently working on a Bootstrap 5 for Internet Explorer 11 solution (which is working really well already). https://github.com/coliff/bootstrap-ie11

I'm also going to update my Bootstrap Show Password Toggle project with a Bootstrap 5 example. https://github.com/coliff/bootstrap-show-password-toggle

**Comment by 9mido** [comment]
Awesome thanks!

**Comment by coliff** [comment]
Fixed with #59
