### ISSUE TITLE
Changes not taking effect on body element

### ISSUE THREAD

**Issue by NicolaiVerbaarschot** [coliff/dark-mode-switch#33]
![screenshot](https://user-images.githubusercontent.com/43202406/87916991-884d3600-ca74-11ea-948f-ba0dd1995d35.png)
![screenshot2](https://user-images.githubusercontent.com/43202406/87917101-ba5e9800-ca74-11ea-81ed-db35baebb399.png)

Hello, firstly, thanks for sharing the project, it is nice, lightweight, and works well. I do have one issue however. I am trying to apply dark-mode styles directly to the body tag and this doesn't seem to work. You can see from my screenshots, that I am able to make the text inside .content red, but when trying to change the gradient to white on the body, I see no changes. I could imagine that this has something to do with the fact that the data-theme attribute is set on the body and then it maybe isn't possible to use in this way. If this is the case, do you know of a workaround? Any help is greatly appreciated.

**Comment by NicolaiVerbaarschot** [comment]
I managed to solve this by wrapping all my body content in a div, and then target that div with the styles. However I would still very much interested if you know the reason for this. Thanks for your time. You can go ahead and close the issue once you've had a look.

**Comment by coliff** [comment]
heya- I'd be happy to help out on this but can you please put together a reduced test case on Codepen or similar for me to look into it? Also, I think the rule defining the background body gradient should really be 'background-image' rather than the shorthand 'background'.

Also, make sure you don't use the dark-mode/css provided in this repo - if you're setting your own styles. If you have the background-color: #111 !important; will be over-riding it!

**Comment by NicolaiVerbaarschot** [comment]
Thanks for the response! I'm not really front-end dev but A colleague of mine just on vacation so I'm taking on some of the tasks. So I will go ahead with your recommendation and use background-image, cheers. I've set up a code pen with a minimal example showcasing the issue [here](https://codepen.io/bowamphora/pen/pogqbKK)

**Comment by coliff** [comment]
ah, I figured it. :-)
To apply the styles to the body you just need:
```
[data-theme=dark]  {
  background-image: white;
}
```
The above will apply to the body as the body tag is the element with `[data-theme=dark] `. just tested working with CodePen.

**Comment by NicolaiVerbaarschot** [comment]
Brilliant, I could have sworn I tried that but I must be mistaken. Thanks for the help.

\Nicolai
