### ISSUE TITLE
td elements keep data-theme=dark style, even when not active.

### ISSUE THREAD

**Issue by NicolaiVerbaarschot** [coliff/dark-mode-switch#34]
Me again :) Have a look at [this codpen](https://codepen.io/bowamphora/pen/pogqbKK), the td elements take on the data-theme=dark style despite the attribute being removed from the body.

**Comment by NicolaiVerbaarschot** [comment]
Playing around a bit more with it in my own project, it appears that the td elements will just take on the final style that is applied, and don't seem to be at all effected by the bodys attribute.

**Comment by coliff** [comment]
ah, your CSS is a bit wrong it should be:
```
[data-theme="dark"] th,
[data-theme="dark"] td {
    color: black;
} 
```
so you need to define [data-theme="dark"] for each rule you want it applied to.

**Comment by NicolaiVerbaarschot** [comment]
Ahh thanks coliff. Yeah my CSS skills aren't quite sharp. Sorry I probably could have solved this one myself if I had put in a bit more effort. Cheers!
