### ISSUE TITLE
how to use this project in react ?

### ISSUE THREAD

**Issue by find456789** [coliff/dark-mode-switch#38]
thank you very much

**Comment by coliff** [comment]
I don't use React myself, so I can't offer any assistance... but I'll leave this issue open for now in case anyone else can offer any guidance / suggestions.

**Comment by UsmanAhmadSaeed** [comment]
Hey, I've recently learned React and can take a look into this. Will update soon

**Comment by max-programming** [comment]
@UsmanAhmadSaeed Hi! My name is also Usman. Anyways, I have a good knowledge of React. Maybe I can help. But, I would not recommend building this with React. As it is a pretty small project, and that's why you shouldn't use React. As you won't be using much features in React. And that can keep the other features of React lazy and can slow down your site... I think vanilla is too good for this kind of project

**Comment by UsmanAhmadSaeed** [comment]
@max-programming Glad to know that.
Thanks about the info. I don't really know how to integrate this for use in React. I'm gonna be pretty busy these days and probably for the foreseeable future so you can take up this issue if you want.

**Comment by zedtux** [comment]
Here is how I've implemented it:

1. Download the `dark-mode.css` file and import it accordingly to your setup (in my case webpack, I've added an import in my javascript of the CSS file)
2. Create a new React component (I'm using Reactstrap):
```javascript
import React, { useState } from 'react'
import { CustomInput } from 'reactstrap'

const ThemeSwitch = () => {
  const localStorageItem = localStorage.getItem('dark-theme-enabled')
  const [darkMode, setDarkMode] = useState(JSON.parse(localStorageItem))

  const toggleDarkMode = () => {
    const newDarkMode = !darkMode
    setDarkMode(newDarkMode)
    localStorage.setItem('dark-theme-enabled', JSON.stringify(newDarkMode))

    if (newDarkMode) {
      document.body.setAttribute('data-theme', 'dark')
    } else {
      document.body.setAttribute('data-theme', '')
    }
  }

  document.body.setAttribute('data-theme', darkMode ? 'dark' : '')

  return (
    <CustomInput
      defaultChecked={darkMode}
      id="theme-switch"
      label="Dark Mode"
      onClick={() => toggleDarkMode()}
      type="switch"
    />
  )
}

export default ThemeSwitch
```
3. Mount that component where you want it
