### ISSUE TITLE
not working on phone

### ISSUE THREAD

**Issue by xujaan** [coliff/dark-mode-switch#39]
trying with different browser still not working

**Comment by coliff** [comment]
hey there - can you please provide more details? What phone/OS/Browser? Do you have a link to the site?

**Comment by xujaan** [comment]
thanks for reply
i'm using android 10 phone, trying with brave and chrome still not working
my website use bootstrap framework, its work on pc browser but not working on phone

**Comment by max-programming** [comment]
@xujaan What happens when you toggle the theme on phone???

**Comment by coliff** [comment]
Please test https://coliff.github.io/dark-mode-switch/ on your phone and provide details if it isn't working.
Does it change colors at all? Does it not store the changed color state after a refresh? Please provide more details so we can help troubleshoot.

**Comment by max-programming** [comment]
It works fine on my end @coliff . Just the heading at the top is not centered. Everything else works fine

**Comment by xujaan** [comment]
sorry its all my fault, it works now. thanks for respond.
