### ISSUE TITLE
How to set dark mode as default

### ISSUE THREAD

**Issue by MG32Codes** [coliff/dark-mode-switch#43]
As the title says.

**Comment by coliff** [comment]
Good question! You could set all the CSS as dark by default, and have the switch 'on' by default. If a user swicthes to 'off' you could load a light-mode CSS instead. It should be quite straight forward, though I may add a separate demo for that at some point.

**Comment by MG32Codes** [comment]
Alright, thanks!

**Comment by ardianta** [comment]
I think just add the `data-theme="dark"` to the `<body>` element. It will set the dark theme as default.

**Comment by crazychatting** [comment]
I think to add the data-theme attribute would not be enough. truly the CSS would show the page with dark style, but the switch would appear off. The initTheme-method needs then to be extended to check if the attribute is already set. Currently only localStorage is checked. But I don´t know yet, if this would be the best solution.
Indeed it would be useful to avoid some flickering or flashing when opening the page, while loading, instead of waiting for JS to be loaded and executed.

**Comment by doniwirawan** [comment]
> I think just add the `data-theme="dark"` to the `<body>` element. It will set the dark theme as default.

but there is a problem with the toggle if we make it like that

**Comment by ardianta** [comment]
> > I think just add the `data-theme="dark"` to the `<body>` element. It will set the dark theme as default.
> 
> but there is a problem with the toggle if we make it like that

Yes, the switch button will not updated.

I created custom script to handle it. See my changes: https://github.com/ardianta/dark-mode-switch/commit/9fad4b93e68d588559cfc898c0411b6665e063aa?branch=9fad4b93e68d588559cfc898c0411b6665e063aa&diff=split

**Comment by doniwirawan** [comment]
thanks mas

**Comment by MrGreensWorkshop** [comment]
When I set dark mode as default, I realized flickering still exist. So I end up saving both "light" or "dark" modes.
hope this helps someone.

dark-mode-switch.js

```
var darkSwitch = document.getElementById("darkSwitch");
window.addEventListener("load", function () {
  if (darkSwitch) {
      var theme = localStorage.getItem("darkSwitch") || document.body.getAttribute('data-theme');
      if ((theme === null) || (theme === "light")){
        darkSwitch.checked = false;
      }else {
        darkSwitch.checked = true;
      }  
      darkSwitch.addEventListener("change", function () {
          resetTheme();
      });
  }
});

function resetTheme() {
  if (darkSwitch.checked) {
      document.body.setAttribute("data-theme", "dark");
      localStorage.setItem("darkSwitch", "dark");
  } else {
    document.body.setAttribute("data-theme", "light");
    localStorage.setItem("darkSwitch", "light");
  }
}
```

dark-mode-init.js
```
function initDarkModeTheme() {
  var theme = localStorage.getItem("darkSwitch") || document.body.getAttribute('data-theme');
  if (theme !== null){
    document.body.setAttribute("data-theme", theme);
  }
}
```


to make dark mode by default add this to "data-theme="dark" <body> tag like below
if you don't need default dark mode by  default use  <body> as it is.
```
<html>
  <head>
  </head>

  <body data-theme="dark">
    <script src="/js/dark-mode-init.js"></script>
    <script type="text/javascript">initDarkModeTheme();</script>

    <p>your content<p>

    <script src="/js/dark-mode-switch.js"></script>
  </body>
</html>
```
