### ISSUE TITLE
Background color of menu dropdown not changing

### ISSUE THREAD

**Issue by Deekee62** [coliff/dark-mode-switch#47]
Hi, I just want to say thanks for writing this code, I just love it!

It seems as there is a tiny problem as the background color of a bootstrap dropdown menu doesn't change its color.

I tried to fix it myself but without any success as I'm still an absolute beginner :-)

Many thanks in advance for any help.

**Comment by Nick390** [comment]
Please review this issue https://github.com/coliff/dark-mode-switch/issues/40 for more details.

**Comment by Deekee62** [comment]
Thanks Nick for your response, that solved my issue, I learned something new today :-)
