### ISSUE TITLE
Does this package registered in cdnjs.com ?

### ISSUE THREAD

**Issue by doniwirawan** [coliff/dark-mode-switch#72]

**Comment by coliff** [comment]
It's not registered in cdnjs.com, but it is available via other CDNs such as:
https://unpkg.com/browse/dark-mode-switch@1.0.0/dark-mode-switch.min.js
https://www.jsdelivr.com/package/npm/dark-mode-switch

Was there a particular reason you enquired about cdnjs.com in particular or where you just interested in loading it via CDN?
